name: Lint Commit Messages
on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: "./.github/commitlint.config.js"
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules
